### ISSUE TITLE
Upgrade frontend dependencies

### ISSUE THREAD

**Issue by dongyuzheng** [rezqio/issues#102]
Remember to test every single functionality we have

**Comment by fannydengdeng** [comment]
Do #94 before upgrading react v17+

**Comment by agapic** [comment]
React 17 isn't released yet, but I can work on upgrading to 16.7

**Comment by dongyuzheng** [comment]
Reopened since there are other deps to upgrade

**Comment by dongyuzheng** [comment]
One example is babel
You can try this: https://github.com/babel/babel-upgrade
I failed trying to upgrade it twice now :')

Some of our other packages are major versions behind

Do not touch and pdf packages (pdf and pdf-annotate); for now
