### ISSUE TITLE
Email notification on critique submit or matched

### ISSUE THREAD

**Issue by dongyuzheng** [rezqio/issues#142]
Notify the critiquee when someone completes a critique for them

1. linked
2. matched
3. pooled

Notifiy a critiquer when they get matched

---

### important

Must allow "opt-out" of emails, or we can get sued

^ prolly just add a flag on the user Model
& add 1 gql endpoint to turn on/off this flag

**Comment by fannydengdeng** [comment]
Have the flag toggle in Settings so it gets carried in the EditProfile
