### ISSUE TITLE
Finish up the pooled critique feature

### ISSUE THREAD

**Issue by dongyuzheng** [rezqio/issues#145]
Base PR by @iyyuan : https://github.com/dongyuzheng/rezq-frontend/pull/134

# Matching is no longer our flagship feature

So the centre shouldn't be "Start a Critique" anymore. Actually, we should hide this for now cuz this will be for verified premium stuff.

![image](https://user-images.githubusercontent.com/6127032/51515404-8653d980-1de1-11e9-8fe4-9c0ec451ab5d.png)

# Revamp the ResumeOverview [DONE]

1. Remove the get critiqued button
2. Replace the Share button with a modal which shows 3 things
   * Share (the link)
   * Pool (enable disable)
   * Match (grayed out, premium only)

![image](https://user-images.githubusercontent.com/6127032/51515470-d59a0a00-1de1-11e9-8fae-6f4ff41723ee.png)

# Revamp the visuals [DONE]

1. especially the upvote/downvote part
    * num upvotes is cached in the backend (on prod; not on dev) for 30 seconds
    * we need to fake and retain some state to give feedback to the user that their upvote/downvote/remove vote went through
        * my idea is to store a local cache cache (ttl=30s) of pooledCritiqueId: numUpvotes
        * and then increment and decrement that based on user action
        * update this cached value after ttl expires

<img width="574" alt="image" src="https://user-images.githubusercontent.com/6127032/51541662-60e9be80-1e27-11e9-8f45-86652c242d62.png">

**Comment by iyyuan** [comment]
https://github.com/rezqio/issues/issues/116 is complete from my end.

As per task description, requires visual overhaul. Also needs to "locally" update the upvote state to provide the sense that the upvote has went through (and it has, but it is cached on the backend and only updated periodically - which is how reddit does it)
