### ISSUE TITLE
Finish up the Welcome Modal

### ISSUE THREAD

**Issue by dongyuzheng** [rezqio/issues#151]
wait for #145 to be done

1. increase height of photos
2. decrease photo font size
3. update photos to reflect 3 things:
    * pooled critique
    * linked critique
    * premium matching critique

<img width="850" alt="image" src="https://user-images.githubusercontent.com/6127032/51582522-6b916b80-1e9a-11e9-90c9-001c69334659.png">

**Comment by iyyuan** [comment]
Marking as done - I pushed straight to master lmao
