### ISSUE TITLE
Don't allow text to go "behind" the copy button

### ISSUE THREAD

**Issue by dongyuzheng** [rezqio/issues#152]
Don't allow text to go "behind" the copy button; we have a few of these modals

<img width="461" alt="image" src="https://user-images.githubusercontent.com/6127032/51583160-3d615b00-1e9d-11e9-95d7-b61500f8d61e.png">

**Comment by ju-de** [comment]
Here's also a fun thing if you squish your window : )

![image](https://user-images.githubusercontent.com/7605884/51644191-5b7e9800-1f3d-11e9-97fb-cf61dc4664b3.png)
