### ISSUE TITLE
Password value should not be seen using Chrome Dev Tools

### ISSUE THREAD

**Issue by stevennx** [rezqio/issues#158]

**Comment by agapic** [comment]
Hey, two questions: is this on prod, or localhost? And, how are you producing this result? 

Nvm, I think you mean in the actual HTML.

Got it.

**Comment by dongyuzheng** [comment]
It must be prod.

**Comment by agapic** [comment]
Closing this: you can always see a password entered in a field. If you try logging in with Gmail, you can see your password there as well.

https://github.com/erikras/redux-form/issues/2417
