### ISSUE TITLE
[Firefox] Clicking on shared pooled-resume link while logged in leads to login screen

### ISSUE THREAD

**Issue by evancoa** [rezqio/issues#159]
Unverified, need to test

**Comment by fannydengdeng** [comment]
GQL issue, looking into it now

**Comment by fannydengdeng** [comment]
Bug has not been successfully reproduced

**Comment by dongyuzheng** [comment]
I cannot reproduce it either

**Comment by iyyuan** [comment]
Closing for now. Maybe my browser is just being weird.
