### ISSUE TITLE
Add previous and next arrows to PDF pagination

### ISSUE THREAD

**Issue by fannydengdeng** [rezqio/issues#164]
Right now it looks like this

<img width="1109" alt="screen shot 2019-01-30 at 10 26 15 pm" src="https://user-images.githubusercontent.com/8739237/52028780-50e47580-24de-11e9-98ab-3a6e39212a29.png">

We want to have it look something like this

<img width="321" alt="screen shot 2019-01-30 at 10 29 32 pm" src="https://user-images.githubusercontent.com/8739237/52028859-a91b7780-24de-11e9-95d3-5dec813fd201.png">

It's unlikely that users will upload a 50-page resume so not a hi pri

**Comment by dongyuzheng** [comment]
man you uploaded a textbook?

**Comment by fannydengdeng** [comment]
I guess it was under 5MB LOL

**Comment by dongyuzheng** [comment]
https://getbootstrap.com/docs/4.0/components/button-group/#button-toolbar
