### ISSUE TITLE
Unsaved changes prompt on sign out when not on a critique

### ISSUE THREAD

**Issue by ju-de** [rezqio/issues#176]
Unsaved changes should be reset after navigating away from page

## Repro:
Press ok to navigate away from a page with unsaved changes
![image](https://user-images.githubusercontent.com/7605884/52334894-ebf1b980-29ce-11e9-9aae-2c8dea2e8355.png)

Try to sign out, prompt appears
![image](https://user-images.githubusercontent.com/7605884/52334904-f4e28b00-29ce-11e9-8688-a2491dc0ea1b.png)

**Comment by evancoa** [comment]
@ju-de which critique page is this?

regular matched, pooled, shared, etc

**Comment by ju-de** [comment]
Anywhere you can type a critique

**Comment by dongyuzheng** [comment]
Related https://github.com/rezqio/issues/issues/204
