### ISSUE TITLE
Text annotations for critique tool does not wrap text

### ISSUE THREAD

**Issue by mokaixu** [rezqio/issues#184]
Text annotations spill over. See image

<img width="216" alt="screen shot 2019-02-13 at 10 46 39 pm" src="https://user-images.githubusercontent.com/19556673/52761413-4e574500-2fe1-11e9-9a0e-19899b0442fe.png">

**Comment by dongyuzheng** [comment]
Related https://github.com/rezqio/issues/issues/127
