### ISSUE TITLE
Add an Accept Terms of Service box to sign up

### ISSUE THREAD

**Issue by ju-de** [rezqio/issues#195]
Additionally, link the terms of service page.

**Comment by dongyuzheng** [comment]
https://termsfeed.com/blog/examples-i-agree-to/

**Comment by agapic** [comment]
I've been thinking, and I don't think we need a checkbox for this as it just adds another step to the signup process. 

What other companies (i.e., FB) are doing is indicating that if you sign up, you agree to the ToS. (https://termsfeed.com/blog/wp-content/uploads/2015/04/facebook-highlight-by-clicking-Sign-up-you-agree.jpg).

I suggest we move the terms of use above the signup button and change the text a bit.
