### ISSUE TITLE
Down chevron on landing page not centered

### ISSUE THREAD

**Issue by dongyuzheng** [rezqio/issues#198]
The degree of not-enteredness changes with screen width :(

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6127032/52965630-45fd6200-3373-11e9-80bf-facb5e389049.png">

**Comment by ju-de** [comment]
![image](https://user-images.githubusercontent.com/7605884/53067755-4729ae80-349b-11e9-9169-a3f768ef08eb.png)
