### ISSUE TITLE
Trying to navigate away from settings triggers unsaved changes prompt

### ISSUE THREAD

**Issue by ju-de** [rezqio/issues#204]
![image](https://user-images.githubusercontent.com/7605884/53145874-a05f1400-3567-11e9-9842-25eba4391eea.png)

Go to settings without changing anything, then try to click away.

**Comment by evancoa** [comment]
Cannot reproduce on chrome, can you clarify full steps of repro? @ju-de

**Comment by ju-de** [comment]
100% repro for me, just go to settings and navigate away. Try a fresh account maybe?

**Comment by evancoa** [comment]
closed because cannot repro consistently

**Comment by evancoa** [comment]
@dongyuzheng can you repro this, because I can't (on latest master, prod, chrome)

otherwise lmk the browser, full steps of repro

**Comment by dongyuzheng** [comment]
I think it's due to autocomplete filling in the username on the Account tab
