### ISSUE TITLE
Only half of the pagination container can be seen on smaller screen sizes

### ISSUE THREAD

**Issue by agapic** [rezqio/issues#212]
![screenshot from 2019-02-25 22-58-13](https://user-images.githubusercontent.com/8027964/53386615-ee518e80-3950-11e9-84c7-7d6e35dee51b.png)

**Comment by dongyuzheng** [comment]
Related https://github.com/rezqio/issues/issues/48

**Comment by evancoa** [comment]
fixed here https://github.com/dongyuzheng/rezq-frontend/pull/218
