### ISSUE TITLE
Header shouldn't be scrollable

### ISSUE THREAD

**Issue by ju-de** [rezqio/issues#220]
You can scroll the header away on My Resumes/My Critiques/Public Pool/Settings (any page using `section-` instead of `splash`).

![image](https://user-images.githubusercontent.com/7605884/53763757-87c0f900-3e99-11e9-8e2a-cd94864b0eb6.png)

**Comment by dongyuzheng** [comment]
I like to ability to scroll it away. Especially on resume/critique pages. The header and footer are distracting.

**Comment by ju-de** [comment]
Then all headers should be scrollable, not just on these pages.

**Comment by evancoa** [comment]
Keeping it on landing because it'll break the landing page chevron scroll. Otherwise every page that uses splash now allows for header/footer scrolling

**Comment by ju-de** [comment]
For chevron scroll, change to `window.scrollTo` instead of `this.splash.scrollTo`.

**Comment by ju-de** [comment]
(and reenable scrolling)

**Comment by evancoa** [comment]
too complicated, merging as is and leaving the landing page as a (super) minor issue since its fine to have the header/footer non scrollable on landing page anyways

**Comment by evancoa** [comment]
@dongyuzheng , confirmed by @ju-de
