### ISSUE TITLE
Limit number and size of resumes uploaded to account

### ISSUE THREAD

**Issue by fannydengdeng** [rezqio/issues#23]
Set a limit on the number of uploaded files as well as max file size.

**Comment by fannydengdeng** [comment]
Somewhat dependent on #8 since we want users to clean up

**Comment by evancoa** [comment]
Setting these values temporarily:

Max uploaded resumes: 2
Max file size: 5mb

**Comment by evancoa** [comment]
Added in this PR: https://github.com/dongyuzheng/rezq-frontend/pull/62
