### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by ErikHumphrey** [rezqio/issues#230]
The site is not available; please open-source it if it is gone for good.

**Comment by dongyuzheng** [comment]
I will discuss with the team.

**Comment by dongyuzheng** [comment]
@ErikHumphrey The project can be open-sourced. Did you want to work on it?

**Comment by ErikHumphrey** [comment]
@dongyuzheng Thanks for the quick reply. I can't say for sure how much time I would spend contributing to it due to not much free time, but it would be nice nonetheless.

**Comment by dongyuzheng** [comment]
@ErikHumphrey The project has been open sourced:
https://github.com/rezqio/rezq-backend
https://github.com/rezqio/rezq-frontend
