### ISSUE TITLE
Create endpoint for a linked critique

### ISSUE THREAD

**Issue by agapic** [rezqio/issues#36]
Allow the user to click a button that takes them directly to critiquing the resume. This will have its own React component. When a user clicks "New Critique" we should re-direct them to the new endpoint, which I'm considering just naming `/sharedCritique/:critiqueToken`

GraphQL endpoints used (expected):
* query `linkedCritique` based on generated token returned from `createLinkedCritique`

Then when we save the critique, we just paste /sharedCritique/:critiqueToken to the original person who sent you the resume token URL, correct? (a reddit user)

@dongyuzheng please confirm.

**Comment by dongyuzheng** [comment]
Confirm.
