### ISSUE TITLE
Initial render of a submitted critique doesn't render resume

### ISSUE THREAD

**Issue by iyyuan** [rezqio/issues#38]
Don't know if this warrants a lot of investigation (tested on Ubuntu 18.04 / firefox), but sometimes when I view the submitted critique, it only displays the annotations and not the resume... Clicking around the dropdown fixes it.

![image](https://user-images.githubusercontent.com/16712961/50580225-f6da8c80-0e19-11e9-888f-fe11e86a093a.png)

Get the following error:

```
Error: Cannot use the same canvas during multiple render() operations. Use different canvas or ensure previous operations were cancelled or completed.
```

**Comment by fannydengdeng** [comment]
@iyyuan can't seem to repro on osx/firefox. do you have a specific scenario where this happens?

**Comment by iyyuan** [comment]
Probably OK to ignore this issue for now unless I can consistently reproduce this issue. It occurred maybe... 1 in 10 tries?

No particular scenario other than opening the critiqued resume and not seeing it load.
