### ISSUE TITLE
Change all lodash import to _

### ISSUE THREAD

**Issue by dongyuzheng** [rezqio/issues#39]
It seems the status quo for using lodash is importing it as `_`, rather than importing, for example, `forEach` directly. https://lodash.com/

**Comment by fannydengdeng** [comment]
@dongyuzheng the advantage of importing lodash as `_` is so we don't have to maintain the individual functions. Doing this will increase the bundle size. Are we sure we want to do this?

**Comment by dongyuzheng** [comment]
It does? I thought npm build is smart enough to solve that problem

**Comment by dongyuzheng** [comment]
Did you compare the sizes?

**Comment by fannydengdeng** [comment]
A quick comparison using webpack-bundle-analyzer

Entire library import

<img width="590" alt="screen shot 2019-01-04 at 3 41 56 pm" src="https://user-images.githubusercontent.com/8739237/50710197-4bf3e980-1038-11e9-89d7-7c963751b2d1.png">

Specific import (ex `import map from 'lodash/map'`)

<img width="274" alt="screen shot 2019-01-04 at 3 47 56 pm" src="https://user-images.githubusercontent.com/8739237/50710210-57471500-1038-11e9-9f6c-6dc01f192f93.png">

^we currently import as `import { map } from 'lodash'`, which is actually not correct. Easy migration though.

**Comment by fannydengdeng** [comment]
I will create a PR after the chips thing is merged (too many conflicts)
