### ISSUE TITLE
Fix private graphql client to not be instansiated on every single call

### ISSUE THREAD

**Issue by dongyuzheng** [rezqio/issues#41]
This will also fix the 10000000 csrf calls:

![image](https://user-images.githubusercontent.com/6127032/50670132-645ff780-0f97-11e9-9cce-ea3b83889bdb.png)

**Comment by fannydengdeng** [comment]
I can do it when I get time, or if anyone needs context I can help

**Comment by dongyuzheng** [comment]
@iyyuan you want to do this?
