### ISSUE TITLE
Issues with current password input on profile edit

### ISSUE THREAD

**Issue by dongyuzheng** [rezqio/issues#43]
If you create an account with Facebook or something, you have no password
but you can't change your password without a password

**Comment by dongyuzheng** [comment]
We should add a "hasPassword: Boolean" field to the ProfileType, so that the frontend can reflect this properly

**Comment by fannydengdeng** [comment]
@dongyuzheng if we are logging in with CAS/FB/Google then there's no use in creating or changing a password that doesn't exist right? Until we've merged the accounts that is.. 

Then we could just disable the password settings in the frontend if they don't have an email?

**Comment by dongyuzheng** [comment]
What if I want to set a password?

**Comment by fannydengdeng** [comment]
If you're setting a password for fun, then the user would just enter one field of New Password, and save? Or they leave "Current Password" as empty...

Also can you confirm that by if email is null, then no password is set on the account? Wondering if there are cases where this is false

**Comment by dongyuzheng** [comment]
Hmm

If they sign up with email, then there is a password for sure
If they sign up with anything else, then there is no password

I guess the use case for this would be to set either
* both email and password
* or both username and password
(to enable email/username log in)

-----

Aside, lemme check what happens when trying to log in someone with email / username, but they didn't set a password.
