### ISSUE TITLE
Adjust footer placement

### ISSUE THREAD

**Issue by dongyuzheng** [rezqio/issues#48]
Firstly, it currently cuts off the bottom bit of the resume (BUG)

Second, having a floating footer fixed absolutely to the bottom is annoying.

Resumes have large vertical height, and having the footer take up these valuable pixels is bad.

=> recommend adjusting footer placement

1) if content is "short", expand empty space, fix to bottom
2) if content is "long", append to bottom of the page (non-floating)

**The footer is also pretty ugly wrt its design**

On mobile with keyboard

<img width="373" alt="image" src="https://user-images.githubusercontent.com/6127032/51049268-64658600-159b-11e9-8b9b-1f9ca3b0748f.png">

It shouldn't come up

**Comment by evancoa** [comment]
After testing, it is much too difficult to employ your "sticky behavior", as we have inconsistent layouts on our routes (that is, the body of each route page is slightly different in terms of size from one another, and it is difficult to code css that's "smart enough" to deal with it)

I can apply a styling that will avoid the footer cutting off the resume, and whatever is long, but the floating heading will need to stay. If we don't use a floating header, we will run into many problems with the header on different screen resolutions, and browser zooms.

Your decision maestro? @dongyuzheng
