### ISSUE TITLE
Remove industries from a resume critique request

### ISSUE THREAD

**Issue by dongyuzheng** [rezqio/issues#67]
And have it use the industries from this resume

<img width="475" alt="image" src="https://user-images.githubusercontent.com/6127032/50721247-4b843e80-108a-11e9-9f63-08997e0e9818.png">

Each resume has associated industries assigned on upload.

There's no need to enter this information twice.

**Comment by fannydengdeng** [comment]
@dongyuzheng if we kill this then the user can't open parallel critique streams for different industries. Unless we want to prevent that, but I don't see why not.
