### ISSUE TITLE
Change resume critique list to not be dropdown

### ISSUE THREAD

**Issue by dongyuzheng** [rezqio/issues#69]
* Make this a clickable row. Show the status on the right side in smaller gray font
* Is the row label the critique ID? if so, change that to 1,2,3,4; cuz we can have 1,5,7,10 if it's the critique id
    * Also just having a number is kinda ugly (@ju-de )

<img width="573" alt="image" src="https://user-images.githubusercontent.com/6127032/50721266-addd3f00-108a-11e9-8ee1-db9216f716f9.png">

**Comment by fannydengdeng** [comment]
@dongyuzheng where should we put the summary/score information for submitted critiques?

**Comment by dongyuzheng** [comment]
Ohhb right.
