### ISSUE TITLE
Frontend crash after submit request for critique

### ISSUE THREAD

**Issue by dongyuzheng** [rezqio/issues#84]
1. go to resume overview page
2. try to request a critique

![image](https://user-images.githubusercontent.com/6127032/50843016-ed7b8380-1335-11e9-8bbb-ed31166745e1.png)

**Comment by fannydengdeng** [comment]
@dongyuzheng cannot repro on fresh account

What I did:
1. Upload resume
2. (redirected to Resume Overview) Click on Get Critiqued to request critique
3. Submission without error

Were your steps slightly different?

**Comment by dongyuzheng** [comment]
Works again >.<
