### ISSUE TITLE
Delete critique on My Critiques page

### ISSUE THREAD

**Issue by dongyuzheng** [rezqio/issues#87]
```
mutation { deleteCritique(critique_id : <id>) { errors } }
```

**Comment by dongyuzheng** [comment]
Do we even want this

**Comment by fannydengdeng** [comment]
Would this be for when they accidentally submit an unwanted/unfinished critique? If it's unfinished there's no guaranteed way for them to get the same match. If it's unwanted then they shouldn't be critiquer. Either way they would have to reach out to us to make changes. Users shouldn't have this much power.
