### ISSUE TITLE
Changing password via Account settings should require new pass twice

### ISSUE THREAD

**Issue by iyyuan** [rezqio/issues#88]
![image](https://user-images.githubusercontent.com/16712961/50868006-7bc62880-137b-11e9-8401-a181ff98ace3.png)

Current change password form is unacceptable. Easy to make a typo and get locked out of your account.

For example, the github form looks like this:

![image](https://user-images.githubusercontent.com/16712961/50868030-9b5d5100-137b-11e9-8974-bbd9e33649f1.png)

**Comment by fannydengdeng** [comment]
We will want a 'Confirm new password' on the signup form and future password reset form as well.
