### ISSUE TITLE
Proper error message for inactive session

### ISSUE THREAD

**Issue by ju-de** [rezqio/issues#98]
If user is auto-signed out, they currently get two popups with unsanitized errors.

![image](https://user-images.githubusercontent.com/7605884/50997957-00d44d80-14f4-11e9-9f80-ce3262a0c8c0.png)

**Comment by dongyuzheng** [comment]
Ah this is fine. Only on dev do we show these popups.

https://github.com/dongyuzheng/rezq-frontend/blob/master/src/GqlClients.jsx#L15
